name: Validate pull request before putting into queue

on:
  pull_request:
  merge_group:

jobs:

  validate-pr:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        echo "pull request!"
        pwd
        tree -a -I '.git'
        git status
    - name: Run fast CI (emulated by a short sleep)
      if: ${{ github.event_name == 'pull_request' }}
      run: sleep 5
    - name: Run merge group stuff
      if: ${{ github.event_name == 'merge_group' }}
      run: |
        echo "Merge group!"
        exit 0
