name: Validate queue

on:
  merge_group:

jobs:

  validate-queue:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        echo "merge queue check!!"
        pwd
        tree -a -I '.git'
        git status
    - name: Run fast CI (emulated by a short sleep)
      run: |
        exit 1
        sleep 30
